package view;

import controller.ControllerAdmin;
import java.awt.Image;
import java.util.ArrayList;
import javax.swing.DefaultComboBoxModel;
import javax.swing.ImageIcon;
import javax.swing.JFileChooser;
import javax.swing.JLabel;
import javax.swing.JOptionPane;
import model.Logined;
import model.Produk;
import model.Size;

public class Admin extends javax.swing.JFrame {
    private String pathCreate = "C:\\TubesHydraCorp\\image\\noImage.png";
    private String pathUpdate = "";
    private ArrayList<Produk> listUpdate;
    private ArrayList<Produk> listDelete;
    private ArrayList<Produk> listShow;
    private Size sizeUpdate = null;
    
    public Admin() {
        initComponents();
        
        setImageProduk(imageProdukI, this.pathCreate);
        showSetDataList();
    }
    
    private void setImageProduk(JLabel label, String path){
        ImageIcon icon = new ImageIcon(path);
        Image img = icon.getImage();
        Image imgScale = img.getScaledInstance(250, 170, Image.SCALE_SMOOTH);
        ImageIcon scaledIcon = new ImageIcon(imgScale);
        label.setIcon(scaledIcon);
    }
    
    public void clearText(){
        this.pathCreate = "C:\\TubesHydraCorp\\image\\noImage.png";
        TextFieldStok.setText("");
        TextFieldHarga.setText("");
        TextFieldNamaProduct.setText("");
        TextFieldProductID.setText("");
        TextFieldSize.setText("");
    }
    
    public void showSetDataList(){
        new ControllerAdmin(this).showDataProduk(listUpdateProduk, listShowProduk);
        this.listUpdate = new ControllerAdmin(this).getAllProduk();
        this.listDelete = new ControllerAdmin(this).getAllProduk();
        this.listShow = new ControllerAdmin(this).getAllProduk();
    }
    
    private void getProdukUpdate(){
        Produk produkU = listUpdate.get(listUpdateProduk.getSelectedIndex());
        this.pathUpdate = produkU.getPath();
        textFieldHargaU.setText(String.valueOf(produkU.getHarga()));
        textFieldNamaU.setText(produkU.getNamaproduk());
        
        DefaultComboBoxModel model = new DefaultComboBoxModel();
        
        this.sizeUpdate = produkU.getSizeProduk().get(0);
        
        for(Size size: produkU.getSizeProduk()){
            model.addElement(size.getSize());
        }
        
        setImageProduk(imageProdukU, this.pathUpdate);
        chooseSize.setModel(model);
        labelStokU.setText(String.valueOf(this.sizeUpdate.getStok()));
        textFieldSizeU.setText(String.valueOf(this.sizeUpdate.getSize()));
    }
    
    private void getProdukShow(){
        Produk produkU = listShow.get(listShowProduk.getSelectedIndex());
        this.pathUpdate = produkU.getPath();
        TextFieldHargaS.setText(String.valueOf(produkU.getHarga()));
        TextFieldNamaS.setText(produkU.getNamaproduk());
        textFieldIdS.setText(produkU.getIdproduk());
        TextFieldSizeS.setText(String.valueOf(produkU.getSizeProduk().get(0).getSize()));
        TextFieldStokS.setText(String.valueOf(produkU.getSizeProduk().get(0).getStok()));
        
        DefaultComboBoxModel model = new DefaultComboBoxModel();
        
        this.sizeUpdate = produkU.getSizeProduk().get(0);
        
        for(Size size: produkU.getSizeProduk()){
            model.addElement(size.getSize());
        }
        
        setImageProduk(imageProdukS, this.pathUpdate);
        chooseSize.setModel(model);
    }
    
    private void refreshTextStok(){
        Produk produk = listUpdate.get(listUpdateProduk.getSelectedIndex());
        Size size = produk.getSizeProduk().get(chooseSize.getSelectedIndex());
        labelStokU.setText(String.valueOf(size.getStok()));
        textFieldSizeU.setText(String.valueOf(size.getSize()));
    }
    
    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        FramePane = new javax.swing.JTabbedPane();
        CreateProductPanel = new javax.swing.JPanel();
        TextFieldProductID = new javax.swing.JTextField();
        TextFieldNamaProduct = new javax.swing.JTextField();
        labelTitleCreate = new javax.swing.JLabel();
        btnClear = new javax.swing.JButton();
        TextFieldHarga = new javax.swing.JTextField();
        TextFieldSize = new javax.swing.JTextField();
        TextFieldStok = new javax.swing.JTextField();
        btnCreate = new javax.swing.JButton();
        jLabel1 = new javax.swing.JLabel();
        imageProdukI = new javax.swing.JLabel();
        buttonChangeI = new javax.swing.JButton();
        UpdateProductPanel = new javax.swing.JPanel();
        jScrollPane2 = new javax.swing.JScrollPane();
        listUpdateProduk = new javax.swing.JList<>();
        labelProductList1 = new javax.swing.JLabel();
        labelTitleUpdate = new javax.swing.JLabel();
        btnUpdate = new javax.swing.JButton();
        ShowIDUpdate = new javax.swing.JLabel();
        labelShowNamaUpdate = new javax.swing.JLabel();
        ShowNamaUpdate = new javax.swing.JLabel();
        labelShowStokupdate = new javax.swing.JLabel();
        ShowStokUpdate = new javax.swing.JLabel();
        labelShowHargaupdate = new javax.swing.JLabel();
        ShowHargaupdate = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        jLabel5 = new javax.swing.JLabel();
        textFieldHargaU = new javax.swing.JTextField();
        textFieldNamaU = new javax.swing.JTextField();
        jLabel6 = new javax.swing.JLabel();
        imageProdukU = new javax.swing.JLabel();
        buttonChangeU = new javax.swing.JButton();
        buttonChangeSize = new javax.swing.JLabel();
        jLabel7 = new javax.swing.JLabel();
        chooseSize = new javax.swing.JComboBox<>();
        labelShowHargaupdate2 = new javax.swing.JLabel();
        labelStokU = new javax.swing.JLabel();
        labelShowStokupdate2 = new javax.swing.JLabel();
        countStok = new javax.swing.JSpinner();
        jLabel8 = new javax.swing.JLabel();
        textFieldSizeU = new javax.swing.JTextField();
        btnDelete = new javax.swing.JButton();
        ShowProductPanel = new javax.swing.JPanel();
        jScrollPane1 = new javax.swing.JScrollPane();
        listShowProduk = new javax.swing.JList<>();
        labelProductList = new javax.swing.JLabel();
        ShowID = new javax.swing.JLabel();
        ShowNama = new javax.swing.JLabel();
        ShowStok = new javax.swing.JLabel();
        labelTitleShow = new javax.swing.JLabel();
        textFieldIdS = new javax.swing.JTextField();
        TextFieldNamaS = new javax.swing.JTextField();
        TextFieldSizeS = new javax.swing.JTextField();
        TextFieldStokS = new javax.swing.JTextField();
        TextFieldHargaS = new javax.swing.JTextField();
        imageProdukS = new javax.swing.JLabel();
        btnLogout = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setTitle("HYDRA Admin");
        getContentPane().setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        CreateProductPanel.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        TextFieldProductID.setFont(new java.awt.Font("Tahoma", 0, 12)); // NOI18N
        TextFieldProductID.setToolTipText("");
        TextFieldProductID.setBorder(javax.swing.BorderFactory.createTitledBorder(null, "ID Produk", javax.swing.border.TitledBorder.DEFAULT_JUSTIFICATION, javax.swing.border.TitledBorder.DEFAULT_POSITION, new java.awt.Font("Tahoma", 0, 12))); // NOI18N
        CreateProductPanel.add(TextFieldProductID, new org.netbeans.lib.awtextra.AbsoluteConstraints(270, 50, 307, 50));

        TextFieldNamaProduct.setBorder(javax.swing.BorderFactory.createTitledBorder(null, "Nama Produk", javax.swing.border.TitledBorder.DEFAULT_JUSTIFICATION, javax.swing.border.TitledBorder.DEFAULT_POSITION, new java.awt.Font("Tahoma", 0, 12))); // NOI18N
        TextFieldNamaProduct.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                TextFieldNamaProductMouseClicked(evt);
            }
        });
        CreateProductPanel.add(TextFieldNamaProduct, new org.netbeans.lib.awtextra.AbsoluteConstraints(270, 110, 307, 50));

        labelTitleCreate.setFont(new java.awt.Font("Cascadia Code", 1, 24)); // NOI18N
        labelTitleCreate.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        labelTitleCreate.setText("HYDRA CORP");
        labelTitleCreate.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                labelTitleCreateMouseEntered(evt);
            }
        });
        CreateProductPanel.add(labelTitleCreate, new org.netbeans.lib.awtextra.AbsoluteConstraints(270, 10, 310, -1));

        btnClear.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        btnClear.setText("Clear");
        btnClear.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                btnClearMouseClicked(evt);
            }
        });
        btnClear.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnClearActionPerformed(evt);
            }
        });
        CreateProductPanel.add(btnClear, new org.netbeans.lib.awtextra.AbsoluteConstraints(140, 310, 120, 40));

        TextFieldHarga.setBorder(javax.swing.BorderFactory.createTitledBorder(null, "Harga", javax.swing.border.TitledBorder.DEFAULT_JUSTIFICATION, javax.swing.border.TitledBorder.DEFAULT_POSITION, new java.awt.Font("Tahoma", 0, 12))); // NOI18N
        TextFieldHarga.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                TextFieldHargaMouseClicked(evt);
            }
        });
        CreateProductPanel.add(TextFieldHarga, new org.netbeans.lib.awtextra.AbsoluteConstraints(270, 300, 307, 50));

        TextFieldSize.setBorder(javax.swing.BorderFactory.createTitledBorder(null, "Size", javax.swing.border.TitledBorder.DEFAULT_JUSTIFICATION, javax.swing.border.TitledBorder.DEFAULT_POSITION, new java.awt.Font("Tahoma", 0, 12))); // NOI18N
        TextFieldSize.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                TextFieldSizeMouseClicked(evt);
            }
        });
        CreateProductPanel.add(TextFieldSize, new org.netbeans.lib.awtextra.AbsoluteConstraints(270, 170, 307, 50));

        TextFieldStok.setBorder(javax.swing.BorderFactory.createTitledBorder(null, "Stok", javax.swing.border.TitledBorder.DEFAULT_JUSTIFICATION, javax.swing.border.TitledBorder.DEFAULT_POSITION, new java.awt.Font("Tahoma", 0, 12))); // NOI18N
        TextFieldStok.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                TextFieldStokMouseClicked(evt);
            }
        });
        CreateProductPanel.add(TextFieldStok, new org.netbeans.lib.awtextra.AbsoluteConstraints(270, 230, 307, 50));

        btnCreate.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        btnCreate.setText("Create");
        btnCreate.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                btnCreateMouseClicked(evt);
            }
        });
        btnCreate.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnCreateActionPerformed(evt);
            }
        });
        CreateProductPanel.add(btnCreate, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 310, 120, 40));

        jLabel1.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        jLabel1.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel1.setText("Gambar Produk");
        CreateProductPanel.add(jLabel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 30, 250, -1));
        CreateProductPanel.add(imageProdukI, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 60, 250, 170));

        buttonChangeI.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        buttonChangeI.setText("Change Image");
        buttonChangeI.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                buttonChangeIActionPerformed(evt);
            }
        });
        CreateProductPanel.add(buttonChangeI, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 250, 230, 40));

        FramePane.addTab("Create Product", CreateProductPanel);

        UpdateProductPanel.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        listUpdateProduk.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                listUpdateProdukMouseClicked(evt);
            }
        });
        jScrollPane2.setViewportView(listUpdateProduk);

        UpdateProductPanel.add(jScrollPane2, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 31, 198, 170));

        labelProductList1.setText("List Produk:");
        UpdateProductPanel.add(labelProductList1, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 11, -1, -1));

        labelTitleUpdate.setFont(new java.awt.Font("Cascadia Code", 1, 24)); // NOI18N
        labelTitleUpdate.setText("HYDRA CORP");
        UpdateProductPanel.add(labelTitleUpdate, new org.netbeans.lib.awtextra.AbsoluteConstraints(200, 0, 160, 30));

        btnUpdate.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        btnUpdate.setText("Update");
        btnUpdate.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                btnUpdateMouseClicked(evt);
            }
        });
        btnUpdate.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnUpdateActionPerformed(evt);
            }
        });
        UpdateProductPanel.add(btnUpdate, new org.netbeans.lib.awtextra.AbsoluteConstraints(180, 300, 120, 50));
        UpdateProductPanel.add(ShowIDUpdate, new org.netbeans.lib.awtextra.AbsoluteConstraints(350, 51, -1, -1));

        labelShowNamaUpdate.setText("Nama");
        UpdateProductPanel.add(labelShowNamaUpdate, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 210, -1, 20));
        UpdateProductPanel.add(ShowNamaUpdate, new org.netbeans.lib.awtextra.AbsoluteConstraints(350, 82, -1, -1));

        labelShowStokupdate.setText("Tambah Stok  : ");
        UpdateProductPanel.add(labelShowStokupdate, new org.netbeans.lib.awtextra.AbsoluteConstraints(160, 240, -1, 20));
        UpdateProductPanel.add(ShowStokUpdate, new org.netbeans.lib.awtextra.AbsoluteConstraints(350, 107, -1, -1));

        labelShowHargaupdate.setText("Harga");
        UpdateProductPanel.add(labelShowHargaupdate, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 270, -1, 20));
        UpdateProductPanel.add(ShowHargaupdate, new org.netbeans.lib.awtextra.AbsoluteConstraints(350, 132, -1, -1));

        jLabel2.setText(":");
        UpdateProductPanel.add(jLabel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(100, 270, 10, 20));

        jLabel4.setText(":");
        UpdateProductPanel.add(jLabel4, new org.netbeans.lib.awtextra.AbsoluteConstraints(100, 210, 10, 20));

        jLabel5.setText(":");
        UpdateProductPanel.add(jLabel5, new org.netbeans.lib.awtextra.AbsoluteConstraints(100, 240, 10, 20));
        UpdateProductPanel.add(textFieldHargaU, new org.netbeans.lib.awtextra.AbsoluteConstraints(110, 270, 190, -1));
        UpdateProductPanel.add(textFieldNamaU, new org.netbeans.lib.awtextra.AbsoluteConstraints(110, 210, 190, -1));

        jLabel6.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        jLabel6.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel6.setText("Gambar Produk");
        UpdateProductPanel.add(jLabel6, new org.netbeans.lib.awtextra.AbsoluteConstraints(360, 10, 180, -1));
        UpdateProductPanel.add(imageProdukU, new org.netbeans.lib.awtextra.AbsoluteConstraints(330, 30, 250, 170));

        buttonChangeU.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        buttonChangeU.setText("Change Image");
        buttonChangeU.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                buttonChangeUActionPerformed(evt);
            }
        });
        UpdateProductPanel.add(buttonChangeU, new org.netbeans.lib.awtextra.AbsoluteConstraints(340, 210, 230, 40));

        buttonChangeSize.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        buttonChangeSize.setText("Change Size");
        UpdateProductPanel.add(buttonChangeSize, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 330, 60, 20));

        jLabel7.setText(":");
        UpdateProductPanel.add(jLabel7, new org.netbeans.lib.awtextra.AbsoluteConstraints(100, 330, 10, 20));

        chooseSize.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                chooseSizeActionPerformed(evt);
            }
        });
        UpdateProductPanel.add(chooseSize, new org.netbeans.lib.awtextra.AbsoluteConstraints(110, 300, 60, -1));

        labelShowHargaupdate2.setText("Size");
        UpdateProductPanel.add(labelShowHargaupdate2, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 300, -1, 20));

        labelStokU.setText("Stok");
        UpdateProductPanel.add(labelStokU, new org.netbeans.lib.awtextra.AbsoluteConstraints(110, 240, 40, 20));

        labelShowStokupdate2.setText("Stok");
        UpdateProductPanel.add(labelShowStokupdate2, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 240, -1, 20));
        UpdateProductPanel.add(countStok, new org.netbeans.lib.awtextra.AbsoluteConstraints(240, 240, 60, -1));

        jLabel8.setText(":");
        UpdateProductPanel.add(jLabel8, new org.netbeans.lib.awtextra.AbsoluteConstraints(100, 300, 10, 20));
        UpdateProductPanel.add(textFieldSizeU, new org.netbeans.lib.awtextra.AbsoluteConstraints(110, 330, 60, -1));

        btnDelete.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        btnDelete.setText("Delete");
        btnDelete.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                btnDeleteMouseClicked(evt);
            }
        });
        btnDelete.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnDeleteActionPerformed(evt);
            }
        });
        UpdateProductPanel.add(btnDelete, new org.netbeans.lib.awtextra.AbsoluteConstraints(310, 300, 120, 50));

        FramePane.addTab("Manipulasi Produk", UpdateProductPanel);

        ShowProductPanel.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        listShowProduk.setModel(new javax.swing.AbstractListModel<String>() {
            String[] strings = { "Item 1", "Item 2", "Item 3", "Item 4", "Item 5" };
            public int getSize() { return strings.length; }
            public String getElementAt(int i) { return strings[i]; }
        });
        listShowProduk.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                listShowProdukMouseClicked(evt);
            }
        });
        jScrollPane1.setViewportView(listShowProduk);

        ShowProductPanel.add(jScrollPane1, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 210, 250, 150));

        labelProductList.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        labelProductList.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        labelProductList.setText("List Produk");
        ShowProductPanel.add(labelProductList, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 190, 240, 20));
        ShowProductPanel.add(ShowID, new org.netbeans.lib.awtextra.AbsoluteConstraints(332, 44, -1, -1));
        ShowProductPanel.add(ShowNama, new org.netbeans.lib.awtextra.AbsoluteConstraints(330, 75, -1, -1));
        ShowProductPanel.add(ShowStok, new org.netbeans.lib.awtextra.AbsoluteConstraints(330, 100, -1, -1));

        labelTitleShow.setFont(new java.awt.Font("Cascadia Code", 1, 24)); // NOI18N
        labelTitleShow.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        labelTitleShow.setText("HYDRA CORP");
        ShowProductPanel.add(labelTitleShow, new org.netbeans.lib.awtextra.AbsoluteConstraints(272, 9, 300, -1));

        textFieldIdS.setFont(new java.awt.Font("Tahoma", 0, 12)); // NOI18N
        textFieldIdS.setToolTipText("");
        textFieldIdS.setBorder(javax.swing.BorderFactory.createTitledBorder(null, "ID Produk", javax.swing.border.TitledBorder.DEFAULT_JUSTIFICATION, javax.swing.border.TitledBorder.DEFAULT_POSITION, new java.awt.Font("Tahoma", 0, 12))); // NOI18N
        ShowProductPanel.add(textFieldIdS, new org.netbeans.lib.awtextra.AbsoluteConstraints(270, 50, 307, 50));

        TextFieldNamaS.setBorder(javax.swing.BorderFactory.createTitledBorder(null, "Nama Produk", javax.swing.border.TitledBorder.DEFAULT_JUSTIFICATION, javax.swing.border.TitledBorder.DEFAULT_POSITION, new java.awt.Font("Tahoma", 0, 12))); // NOI18N
        TextFieldNamaS.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                TextFieldNamaSMouseClicked(evt);
            }
        });
        ShowProductPanel.add(TextFieldNamaS, new org.netbeans.lib.awtextra.AbsoluteConstraints(270, 110, 307, 50));

        TextFieldSizeS.setBorder(javax.swing.BorderFactory.createTitledBorder(null, "Size", javax.swing.border.TitledBorder.DEFAULT_JUSTIFICATION, javax.swing.border.TitledBorder.DEFAULT_POSITION, new java.awt.Font("Tahoma", 0, 12))); // NOI18N
        TextFieldSizeS.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                TextFieldSizeSMouseClicked(evt);
            }
        });
        ShowProductPanel.add(TextFieldSizeS, new org.netbeans.lib.awtextra.AbsoluteConstraints(270, 170, 307, 50));

        TextFieldStokS.setBorder(javax.swing.BorderFactory.createTitledBorder(null, "Stok", javax.swing.border.TitledBorder.DEFAULT_JUSTIFICATION, javax.swing.border.TitledBorder.DEFAULT_POSITION, new java.awt.Font("Tahoma", 0, 12))); // NOI18N
        TextFieldStokS.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                TextFieldStokSMouseClicked(evt);
            }
        });
        ShowProductPanel.add(TextFieldStokS, new org.netbeans.lib.awtextra.AbsoluteConstraints(270, 230, 307, 50));

        TextFieldHargaS.setBorder(javax.swing.BorderFactory.createTitledBorder(null, "Harga", javax.swing.border.TitledBorder.DEFAULT_JUSTIFICATION, javax.swing.border.TitledBorder.DEFAULT_POSITION, new java.awt.Font("Tahoma", 0, 12))); // NOI18N
        TextFieldHargaS.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                TextFieldHargaSMouseClicked(evt);
            }
        });
        ShowProductPanel.add(TextFieldHargaS, new org.netbeans.lib.awtextra.AbsoluteConstraints(270, 300, 307, 50));
        ShowProductPanel.add(imageProdukS, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 10, 250, 170));

        FramePane.addTab("Show Product", ShowProductPanel);

        getContentPane().add(FramePane, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 597, 412));

        btnLogout.setText("Logout");
        btnLogout.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                btnLogoutMouseClicked(evt);
            }
        });
        getContentPane().add(btnLogout, new org.netbeans.lib.awtextra.AbsoluteConstraints(600, 40, -1, -1));

        pack();
        setLocationRelativeTo(null);
    }// </editor-fold>//GEN-END:initComponents

    private void TextFieldHargaSMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_TextFieldHargaSMouseClicked
        // TODO add your handling code here:
    }//GEN-LAST:event_TextFieldHargaSMouseClicked

    private void TextFieldStokSMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_TextFieldStokSMouseClicked
        // TODO add your handling code here:
    }//GEN-LAST:event_TextFieldStokSMouseClicked

    private void TextFieldSizeSMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_TextFieldSizeSMouseClicked
        // TODO add your handling code here:
    }//GEN-LAST:event_TextFieldSizeSMouseClicked

    private void TextFieldNamaSMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_TextFieldNamaSMouseClicked
        // TODO add your handling code here:
    }//GEN-LAST:event_TextFieldNamaSMouseClicked

    private void btnDeleteActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnDeleteActionPerformed
        // TODO add your handling code here:
        Produk produk = listUpdate.get(listUpdateProduk.getSelectedIndex());
        
        new ControllerAdmin(this).deleteProduk(produk.getIdproduk(), produk.getSizeProduk());
    }//GEN-LAST:event_btnDeleteActionPerformed

    private void btnDeleteMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btnDeleteMouseClicked
        // TODO add your handling code here:
    }//GEN-LAST:event_btnDeleteMouseClicked

    private void chooseSizeActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_chooseSizeActionPerformed
        // TODO add your handling code here:
        refreshTextStok();
    }//GEN-LAST:event_chooseSizeActionPerformed

    private void buttonChangeUActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_buttonChangeUActionPerformed
        // TODO add your handling code here:
        JFileChooser fileChooser = new JFileChooser("C:\\");

            int cek = fileChooser.showOpenDialog(null);
            if(cek == JFileChooser.APPROVE_OPTION){
                this.pathUpdate = fileChooser.getSelectedFile().getAbsolutePath();
            }
            setImageProduk(imageProdukU, pathUpdate);
    }//GEN-LAST:event_buttonChangeUActionPerformed

    private void btnUpdateActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnUpdateActionPerformed
        // TODO add your handling code here:
        if(textFieldHargaU.getText().equals("") || textFieldNamaU.getText().equals("") ||
            textFieldSizeU.getText().equals("")){
            JOptionPane.showMessageDialog(this, "Data kosong");
        }else{
            if(labelStokU.getText().equals("0")){
                JOptionPane.showMessageDialog(this, "Stok Kosong");
            }else{
                Produk produk = listUpdate.get(listUpdateProduk.getSelectedIndex());
                Size size = produk.getSizeProduk().get(chooseSize.getSelectedIndex());
                String nama = textFieldNamaU.getText();
                int stok = Integer.valueOf(labelStokU.getText()) + (int) countStok.getValue();
                int harga = Integer.valueOf(textFieldHargaU.getText());
                int sizeU = Integer.valueOf(textFieldSizeU.getText());

                new ControllerAdmin(this).updateProduk(produk.getIdproduk(), size.getIdsize(),
                    nama, harga, stok, sizeU, this.pathUpdate);
            }
        }
    }//GEN-LAST:event_btnUpdateActionPerformed

    private void btnUpdateMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btnUpdateMouseClicked
        // TODO add your handling code here:

    }//GEN-LAST:event_btnUpdateMouseClicked

    private void listUpdateProdukMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_listUpdateProdukMouseClicked
        // TODO add your handling code here:
        getProdukUpdate();
    }//GEN-LAST:event_listUpdateProdukMouseClicked

    private void buttonChangeIActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_buttonChangeIActionPerformed
        // TODO add your handling code here:
        JFileChooser fileChooser = new JFileChooser("C:\\");

            int cek = fileChooser.showOpenDialog(null);
            if(cek == JFileChooser.APPROVE_OPTION){
                this.pathCreate = fileChooser.getSelectedFile().getAbsolutePath();
            }
            setImageProduk(imageProdukI, this.pathCreate);
    }//GEN-LAST:event_buttonChangeIActionPerformed

    private void btnCreateActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnCreateActionPerformed
        // TODO add your handling code here:
        String idProduk = TextFieldProductID.getText();
        String namaProduk = TextFieldNamaProduct.getText();
        int harga = Integer.parseInt(TextFieldHarga.getText());
        int size = Integer.parseInt(TextFieldSize.getText());
        int stok = Integer.parseInt(TextFieldStok.getText());

        new ControllerAdmin(this).addProduk(idProduk, namaProduk, harga, size, stok, this.pathCreate);
    }//GEN-LAST:event_btnCreateActionPerformed

    private void btnCreateMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btnCreateMouseClicked
        // TODO add your handling code here:
    }//GEN-LAST:event_btnCreateMouseClicked

    private void TextFieldStokMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_TextFieldStokMouseClicked
        // TODO add your handling code here:
    }//GEN-LAST:event_TextFieldStokMouseClicked

    private void TextFieldSizeMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_TextFieldSizeMouseClicked
        // TODO add your handling code here:
    }//GEN-LAST:event_TextFieldSizeMouseClicked

    private void TextFieldHargaMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_TextFieldHargaMouseClicked
        // TODO add your handling code here:
    }//GEN-LAST:event_TextFieldHargaMouseClicked

    private void btnClearActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnClearActionPerformed
        // TODO add your handling code here:
        clearText();
    }//GEN-LAST:event_btnClearActionPerformed

    private void btnClearMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btnClearMouseClicked
        // TODO add your handling code here:

    }//GEN-LAST:event_btnClearMouseClicked

    private void labelTitleCreateMouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_labelTitleCreateMouseEntered
        // TODO add your handling code here:
    }//GEN-LAST:event_labelTitleCreateMouseEntered

    private void TextFieldNamaProductMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_TextFieldNamaProductMouseClicked
        // TODO add your handling code here:

    }//GEN-LAST:event_TextFieldNamaProductMouseClicked

    private void listShowProdukMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_listShowProdukMouseClicked
        // TODO add your handling code here:
        getProdukShow();
    }//GEN-LAST:event_listShowProdukMouseClicked

    private void btnLogoutMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btnLogoutMouseClicked
        // TODO add your handling code here:
        Logined.loginAdmin = null;
        new Login().setVisible(true);
        this.dispose();
        
    }//GEN-LAST:event_btnLogoutMouseClicked
    
    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Windows".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(Admin.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(Admin.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(Admin.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(Admin.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new Admin().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JPanel CreateProductPanel;
    private javax.swing.JTabbedPane FramePane;
    private javax.swing.JLabel ShowHargaupdate;
    private javax.swing.JLabel ShowID;
    private javax.swing.JLabel ShowIDUpdate;
    private javax.swing.JLabel ShowNama;
    private javax.swing.JLabel ShowNamaUpdate;
    private javax.swing.JPanel ShowProductPanel;
    private javax.swing.JLabel ShowStok;
    private javax.swing.JLabel ShowStokUpdate;
    private javax.swing.JTextField TextFieldHarga;
    private javax.swing.JTextField TextFieldHargaS;
    private javax.swing.JTextField TextFieldNamaProduct;
    private javax.swing.JTextField TextFieldNamaS;
    private javax.swing.JTextField TextFieldProductID;
    private javax.swing.JTextField TextFieldSize;
    private javax.swing.JTextField TextFieldSizeS;
    private javax.swing.JTextField TextFieldStok;
    private javax.swing.JTextField TextFieldStokS;
    private javax.swing.JPanel UpdateProductPanel;
    private javax.swing.JButton btnClear;
    private javax.swing.JButton btnCreate;
    private javax.swing.JButton btnDelete;
    private javax.swing.JButton btnLogout;
    private javax.swing.JButton btnUpdate;
    private javax.swing.JButton buttonChangeI;
    private javax.swing.JLabel buttonChangeSize;
    private javax.swing.JButton buttonChangeU;
    private javax.swing.JComboBox<String> chooseSize;
    private javax.swing.JSpinner countStok;
    private javax.swing.JLabel imageProdukI;
    private javax.swing.JLabel imageProdukS;
    private javax.swing.JLabel imageProdukU;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JScrollPane jScrollPane2;
    private javax.swing.JLabel labelProductList;
    private javax.swing.JLabel labelProductList1;
    private javax.swing.JLabel labelShowHargaupdate;
    private javax.swing.JLabel labelShowHargaupdate2;
    private javax.swing.JLabel labelShowNamaUpdate;
    private javax.swing.JLabel labelShowStokupdate;
    private javax.swing.JLabel labelShowStokupdate2;
    private javax.swing.JLabel labelStokU;
    private javax.swing.JLabel labelTitleCreate;
    private javax.swing.JLabel labelTitleShow;
    private javax.swing.JLabel labelTitleUpdate;
    private javax.swing.JList<String> listShowProduk;
    private javax.swing.JList<String> listUpdateProduk;
    private javax.swing.JTextField textFieldHargaU;
    private javax.swing.JTextField textFieldIdS;
    private javax.swing.JTextField textFieldNamaU;
    private javax.swing.JTextField textFieldSizeU;
    // End of variables declaration//GEN-END:variables
}
