/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package view;

import controller.ControllerCart;
import java.text.NumberFormat;
import java.util.Locale;
import javax.swing.JOptionPane;

public class Cart extends javax.swing.JFrame {

    /**
     * Creates new form Wishlist
     */
    private final Home home;
    private model.Cart buyProduk = null;
    public Cart(Home home) {
        initComponents();
        this.home = home;
        
        setBuyText(0);
    }
    
    public void setBuyProduk(model.Cart buyProduk){
        this.buyProduk = buyProduk;
    }
    
    public void setBuyText(int qty){
        new ControllerCart(this.home, this).showCart(panelCart);
        
        if(this.buyProduk == null){
            labelHarga.setVisible(false);
            labelNama.setVisible(false);
            labelQty.setVisible(false);
            labelSize.setVisible(false);
            labelTotalHarga.setText("0");
        }else{
            labelHarga.setVisible(true);
            labelNama.setVisible(true);
            labelQty.setVisible(true);
            labelSize.setVisible(true);
            
            Locale indo = new Locale("in", "ID");
            NumberFormat formatRp = NumberFormat.getCurrencyInstance(indo);
            int totalHarga = this.buyProduk.getProduk().getHarga() * qty;
            
            labelHarga.setText(String.valueOf(this.buyProduk.getProduk().getHarga()));
            labelNama.setText(this.buyProduk.getProduk().getNamaproduk());
            labelQty.setText(String.valueOf(qty));
            labelSize.setText(String.valueOf(this.buyProduk.getSize().getSize()));
            labelTotalHarga.setText(formatRp.format(totalHarga));
        }
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        title3 = new javax.swing.JLabel();
        Back2 = new javax.swing.JLabel();
        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        buttonDelete = new javax.swing.JButton();
        buttonBuy = new javax.swing.JButton();
        jLabel3 = new javax.swing.JLabel();
        labelQty = new javax.swing.JLabel();
        jLabel5 = new javax.swing.JLabel();
        jLabel6 = new javax.swing.JLabel();
        jLabel9 = new javax.swing.JLabel();
        labelTotalHarga = new javax.swing.JLabel();
        jLabel8 = new javax.swing.JLabel();
        labelNama = new javax.swing.JLabel();
        labelSize = new javax.swing.JLabel();
        labelHarga = new javax.swing.JLabel();
        jScrollPane1 = new javax.swing.JScrollPane();
        panelCart = new javax.swing.JPanel();

        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);
        getContentPane().setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jPanel1.setBackground(new java.awt.Color(153, 153, 153));

        title3.setFont(new java.awt.Font("Cascadia Code", 1, 24)); // NOI18N
        title3.setText("HYDRA CORP.");

        Back2.setFont(new java.awt.Font("Cascadia Mono", 1, 24)); // NOI18N
        Back2.setText("<-BACK");
        Back2.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                Back2MouseClicked(evt);
            }
        });

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGap(25, 25, 25)
                .addComponent(title3)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 540, Short.MAX_VALUE)
                .addComponent(Back2)
                .addContainerGap())
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(title3)
                    .addComponent(Back2))
                .addContainerGap(20, Short.MAX_VALUE))
        );

        getContentPane().add(jPanel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 830, 60));

        jLabel1.setFont(new java.awt.Font("Tahoma", 1, 24)); // NOI18N
        jLabel1.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel1.setText("Cart");
        getContentPane().add(jLabel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(460, 80, 360, 40));

        jLabel2.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        jLabel2.setText("Detail Pembelian Produk:");
        getContentPane().add(jLabel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(460, 120, 170, 30));

        buttonDelete.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        buttonDelete.setText("Delete");
        buttonDelete.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                buttonDeleteActionPerformed(evt);
            }
        });
        getContentPane().add(buttonDelete, new org.netbeans.lib.awtextra.AbsoluteConstraints(650, 370, 170, 50));

        buttonBuy.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        buttonBuy.setText("Buy");
        buttonBuy.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                buttonBuyActionPerformed(evt);
            }
        });
        getContentPane().add(buttonBuy, new org.netbeans.lib.awtextra.AbsoluteConstraints(460, 370, 170, 50));

        jLabel3.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        jLabel3.setText("Qty");
        getContentPane().add(jLabel3, new org.netbeans.lib.awtextra.AbsoluteConstraints(520, 250, -1, -1));

        labelQty.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        labelQty.setText("Qty");
        getContentPane().add(labelQty, new org.netbeans.lib.awtextra.AbsoluteConstraints(560, 250, 260, -1));

        jLabel5.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        jLabel5.setText("Harga Produk");
        getContentPane().add(jLabel5, new org.netbeans.lib.awtextra.AbsoluteConstraints(460, 220, -1, -1));

        jLabel6.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        jLabel6.setText("Ukuran");
        getContentPane().add(jLabel6, new org.netbeans.lib.awtextra.AbsoluteConstraints(500, 190, -1, -1));

        jLabel9.setFont(new java.awt.Font("Tahoma", 0, 16)); // NOI18N
        jLabel9.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel9.setText("Total Pembayaran");
        getContentPane().add(jLabel9, new org.netbeans.lib.awtextra.AbsoluteConstraints(462, 280, 360, -1));

        labelTotalHarga.setFont(new java.awt.Font("Tahoma", 0, 20)); // NOI18N
        labelTotalHarga.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        labelTotalHarga.setText("Total Harga");
        getContentPane().add(labelTotalHarga, new org.netbeans.lib.awtextra.AbsoluteConstraints(460, 300, 360, 40));

        jLabel8.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        jLabel8.setText("Nama Produk");
        getContentPane().add(jLabel8, new org.netbeans.lib.awtextra.AbsoluteConstraints(460, 160, -1, -1));

        labelNama.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        labelNama.setText("Nama Produk");
        getContentPane().add(labelNama, new org.netbeans.lib.awtextra.AbsoluteConstraints(560, 160, 260, -1));

        labelSize.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        labelSize.setText("Size");
        getContentPane().add(labelSize, new org.netbeans.lib.awtextra.AbsoluteConstraints(560, 190, 260, -1));

        labelHarga.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        labelHarga.setText("Harga");
        getContentPane().add(labelHarga, new org.netbeans.lib.awtextra.AbsoluteConstraints(560, 220, 260, -1));

        jScrollPane1.setHorizontalScrollBarPolicy(javax.swing.ScrollPaneConstants.HORIZONTAL_SCROLLBAR_NEVER);

        panelCart.setBackground(new java.awt.Color(255, 255, 255));

        javax.swing.GroupLayout panelCartLayout = new javax.swing.GroupLayout(panelCart);
        panelCart.setLayout(panelCartLayout);
        panelCartLayout.setHorizontalGroup(
            panelCartLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 1000, Short.MAX_VALUE)
        );
        panelCartLayout.setVerticalGroup(
            panelCartLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 448, Short.MAX_VALUE)
        );

        jScrollPane1.setViewportView(panelCart);

        getContentPane().add(jScrollPane1, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 80, 450, 450));

        pack();
        setLocationRelativeTo(null);
    }// </editor-fold>//GEN-END:initComponents

    private void Back2MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_Back2MouseClicked
        // TODO add your handling code here:
        new Home().setVisible(true);
        this.home.dispose();
        this.dispose();
    }//GEN-LAST:event_Back2MouseClicked

    private void buttonDeleteActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_buttonDeleteActionPerformed
        // TODO add your handling code here:
        if(this.buyProduk != null){
            new ControllerCart(this.home, this).deleteCart(this.buyProduk.getIdcart());
        }else{
            JOptionPane.showMessageDialog(this, "Pilih salah satu produk");
        }
    }//GEN-LAST:event_buttonDeleteActionPerformed

    private void buttonBuyActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_buttonBuyActionPerformed
        // TODO add your handling code here:
        if(this.buyProduk != null){
            if(Integer.valueOf(labelQty.getText()) > this.buyProduk.getSize().getStok()){
                JOptionPane.showMessageDialog(this, "Stok beli melebih kuota stok produk");
            }else{
                new ControllerCart(this.home, this).buyCart(this.buyProduk, Integer.valueOf(labelQty.getText()));
            }
        }else{
            JOptionPane.showMessageDialog(this, "Pilih salah satu produk");
        }
    }//GEN-LAST:event_buttonBuyActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(Cart.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(Cart.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(Cart.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(Cart.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new Cart(null).setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLabel Back2;
    private javax.swing.JButton buttonBuy;
    private javax.swing.JButton buttonDelete;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JLabel jLabel9;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JLabel labelHarga;
    private javax.swing.JLabel labelNama;
    private javax.swing.JLabel labelQty;
    private javax.swing.JLabel labelSize;
    private javax.swing.JLabel labelTotalHarga;
    private javax.swing.JPanel panelCart;
    private javax.swing.JLabel title3;
    // End of variables declaration//GEN-END:variables
}
