/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package view;
import controller.ControllerProduk;
import java.awt.Image;
import javax.swing.ImageIcon;
import view.BoxProduk;

public class Home extends javax.swing.JFrame {

    /**
     * Creates new form UI
     */
    public Home() {
        initComponents();
        
        //set Image Lifestyle
        ImageIcon icon = new ImageIcon("C:\\TubesHydraCorp\\image\\Lifestyle.jpg");
        Image img = icon.getImage();
        Image imgScale = img.getScaledInstance(imageLf.getWidth(), imageLf.getHeight(), Image.SCALE_SMOOTH);
        ImageIcon scaledIcon = new ImageIcon(imgScale);
        imageLf.setIcon(scaledIcon);
        
        setHome();
    }
    
    public void setHome(){
        new ControllerProduk(this).showProduk(panelProduk);
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel5 = new javax.swing.JPanel();
        jPanel1 = new javax.swing.JPanel();
        jTabbedPane1 = new javax.swing.JTabbedPane();
        panelHome = new javax.swing.JPanel();
        imageHome = new javax.swing.JLabel();
        panelShoes = new javax.swing.JPanel();
        jScrollPane1 = new javax.swing.JScrollPane();
        panelProduk = new javax.swing.JPanel();
        panelLifeStyle = new javax.swing.JPanel();
        jLabel2 = new javax.swing.JLabel();
        jLabel6 = new javax.swing.JLabel();
        imageLf = new javax.swing.JLabel();
        TFsearch = new javax.swing.JTextField();
        btProfile = new javax.swing.JButton();
        btWishlist = new javax.swing.JButton();
        btCarts = new javax.swing.JButton();
        title = new javax.swing.JLabel();

        javax.swing.GroupLayout jPanel5Layout = new javax.swing.GroupLayout(jPanel5);
        jPanel5.setLayout(jPanel5Layout);
        jPanel5Layout.setHorizontalGroup(
            jPanel5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 100, Short.MAX_VALUE)
        );
        jPanel5Layout.setVerticalGroup(
            jPanel5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 100, Short.MAX_VALUE)
        );

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        jPanel1.setBackground(new java.awt.Color(0, 0, 0));
        jPanel1.setPreferredSize(new java.awt.Dimension(900, 500));

        jTabbedPane1.setFont(new java.awt.Font("Schadow BT", 1, 14)); // NOI18N

        panelHome.setPreferredSize(new java.awt.Dimension(900, 500));

        imageHome.setIcon(new javax.swing.ImageIcon("C:\\TubesHydraCorp\\image\\Home.jpg")); // NOI18N

        javax.swing.GroupLayout panelHomeLayout = new javax.swing.GroupLayout(panelHome);
        panelHome.setLayout(panelHomeLayout);
        panelHomeLayout.setHorizontalGroup(
            panelHomeLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(panelHomeLayout.createSequentialGroup()
                .addComponent(imageHome)
                .addGap(0, 1, Short.MAX_VALUE))
        );
        panelHomeLayout.setVerticalGroup(
            panelHomeLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(imageHome, javax.swing.GroupLayout.PREFERRED_SIZE, 846, Short.MAX_VALUE)
        );

        jTabbedPane1.addTab("HOME", panelHome);

        panelShoes.setBackground(new java.awt.Color(255, 255, 255));
        panelShoes.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jScrollPane1.setBackground(new java.awt.Color(255, 255, 255));
        jScrollPane1.setHorizontalScrollBarPolicy(javax.swing.ScrollPaneConstants.HORIZONTAL_SCROLLBAR_NEVER);

        panelProduk.setBackground(new java.awt.Color(255, 255, 255));

        javax.swing.GroupLayout panelProdukLayout = new javax.swing.GroupLayout(panelProduk);
        panelProduk.setLayout(panelProdukLayout);
        panelProdukLayout.setHorizontalGroup(
            panelProdukLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 1348, Short.MAX_VALUE)
        );
        panelProdukLayout.setVerticalGroup(
            panelProdukLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 848, Short.MAX_VALUE)
        );

        jScrollPane1.setViewportView(panelProduk);

        panelShoes.add(jScrollPane1, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 1350, 850));

        jTabbedPane1.addTab("SHOES", panelShoes);

        jLabel2.setFont(new java.awt.Font("Tahoma", 1, 48)); // NOI18N
        jLabel2.setText("LOOK BACK IN 2023");

        jLabel6.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        jLabel6.setText("Move, shop, and celebrate with the best NIKE shoes");

        javax.swing.GroupLayout panelLifeStyleLayout = new javax.swing.GroupLayout(panelLifeStyle);
        panelLifeStyle.setLayout(panelLifeStyleLayout);
        panelLifeStyleLayout.setHorizontalGroup(
            panelLifeStyleLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, panelLifeStyleLayout.createSequentialGroup()
                .addGap(0, 442, Short.MAX_VALUE)
                .addGroup(panelLifeStyleLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, panelLifeStyleLayout.createSequentialGroup()
                        .addComponent(jLabel6)
                        .addGap(492, 492, 492))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, panelLifeStyleLayout.createSequentialGroup()
                        .addComponent(jLabel2)
                        .addGap(415, 415, 415))))
            .addComponent(imageLf, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        panelLifeStyleLayout.setVerticalGroup(
            panelLifeStyleLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, panelLifeStyleLayout.createSequentialGroup()
                .addGap(25, 25, 25)
                .addComponent(jLabel2)
                .addGap(18, 18, 18)
                .addComponent(jLabel6)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(imageLf, javax.swing.GroupLayout.DEFAULT_SIZE, 722, Short.MAX_VALUE))
        );

        jTabbedPane1.addTab("Lifestyle", panelLifeStyle);

        TFsearch.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                TFsearchActionPerformed(evt);
            }
        });

        btProfile.setBackground(new java.awt.Color(255, 255, 255));
        btProfile.setText("Profile");
        btProfile.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btProfileActionPerformed(evt);
            }
        });

        btWishlist.setBackground(new java.awt.Color(255, 255, 255));
        btWishlist.setText("Wishlist");
        btWishlist.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btWishlistActionPerformed(evt);
            }
        });

        btCarts.setBackground(new java.awt.Color(255, 255, 255));
        btCarts.setText("Carts");
        btCarts.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btCartsActionPerformed(evt);
            }
        });

        title.setFont(new java.awt.Font("Bell MT", 1, 24)); // NOI18N
        title.setForeground(new java.awt.Color(255, 255, 255));
        title.setText("HYDRA CORP.");

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGap(30, 30, 30)
                .addComponent(title)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                        .addComponent(btProfile, javax.swing.GroupLayout.PREFERRED_SIZE, 90, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(18, 18, 18)
                        .addComponent(btWishlist)
                        .addGap(18, 18, 18)
                        .addComponent(btCarts, javax.swing.GroupLayout.PREFERRED_SIZE, 77, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(19, 19, 19))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                        .addComponent(TFsearch, javax.swing.GroupLayout.PREFERRED_SIZE, 441, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addContainerGap())))
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addComponent(jTabbedPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 1353, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(0, 0, Short.MAX_VALUE))
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGap(19, 19, 19)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(btProfile)
                            .addComponent(btWishlist)
                            .addComponent(btCarts))
                        .addGap(10, 10, 10)
                        .addComponent(TFsearch, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGap(31, 31, 31)
                        .addComponent(title)))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 18, Short.MAX_VALUE)
                .addComponent(jTabbedPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 879, javax.swing.GroupLayout.PREFERRED_SIZE))
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, 1353, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, 969, javax.swing.GroupLayout.PREFERRED_SIZE)
        );

        pack();
        setLocationRelativeTo(null);
    }// </editor-fold>//GEN-END:initComponents

    private void btWishlistActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btWishlistActionPerformed
        // TODO add your handling code here:
        new Wishlist(this).setVisible(true);
        this.dispose();
    }//GEN-LAST:event_btWishlistActionPerformed

    private void btProfileActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btProfileActionPerformed
        // TODO add your handling code here:
        new Profile().setVisible(true);
        dispose();
    }//GEN-LAST:event_btProfileActionPerformed

    private void btCartsActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btCartsActionPerformed
        // TODO add your handling code here:
        new Cart(this).setVisible(true);
        dispose();
    }//GEN-LAST:event_btCartsActionPerformed

    private void TFsearchActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_TFsearchActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_TFsearchActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        
        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            @Override
            public void run() {
                new Home().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JTextField TFsearch;
    private javax.swing.JButton btCarts;
    private javax.swing.JButton btProfile;
    private javax.swing.JButton btWishlist;
    private javax.swing.JLabel imageHome;
    private javax.swing.JLabel imageLf;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel5;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JTabbedPane jTabbedPane1;
    private javax.swing.JPanel panelHome;
    private javax.swing.JPanel panelLifeStyle;
    private javax.swing.JPanel panelProduk;
    private javax.swing.JPanel panelShoes;
    private javax.swing.JLabel title;
    // End of variables declaration//GEN-END:variables
}
