/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package view;

import controller.ControllerClient;

public class Register extends javax.swing.JFrame {
    /**
     * Creates new form Register
     */
    public Register() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        jPanel2 = new javax.swing.JPanel();
        minimizeRegister = new javax.swing.JLabel();
        xRegister = new javax.swing.JLabel();
        titleRegister = new javax.swing.JLabel();
        labelRegister = new javax.swing.JLabel();
        labelNameregister = new javax.swing.JLabel();
        labelUsernameregister = new javax.swing.JLabel();
        labelPasswordregister = new javax.swing.JLabel();
        labelPasswordregister2 = new javax.swing.JLabel();
        TFnameregister = new javax.swing.JTextField();
        TFusernameregister = new javax.swing.JTextField();
        pwRegister = new javax.swing.JPasswordField();
        pwRegister2 = new javax.swing.JPasswordField();
        btRegister2 = new javax.swing.JButton();
        labelWarning = new javax.swing.JLabel();
        labelAlamat = new javax.swing.JLabel();
        TFAlamatregister = new javax.swing.JTextField();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        jPanel1.setBackground(new java.awt.Color(153, 153, 153));

        jPanel2.setLayout(null);

        minimizeRegister.setFont(new java.awt.Font("Cascadia Mono", 1, 36)); // NOI18N
        minimizeRegister.setText("-");
        minimizeRegister.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                minimizeRegisterMouseClicked(evt);
            }
        });

        xRegister.setFont(new java.awt.Font("Cascadia Mono", 1, 36)); // NOI18N
        xRegister.setText("X");
        xRegister.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                xRegisterMouseClicked(evt);
            }
        });

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel2, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(minimizeRegister)
                .addGap(34, 34, 34)
                .addComponent(xRegister)
                .addGap(28, 28, 28))
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                .addGap(0, 13, Short.MAX_VALUE)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(minimizeRegister)
                    .addComponent(xRegister))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jPanel2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
        );

        titleRegister.setFont(new java.awt.Font("Cascadia Mono", 1, 48)); // NOI18N
        titleRegister.setText("Register");

        labelRegister.setFont(new java.awt.Font("Cascadia Mono", 0, 13)); // NOI18N
        labelRegister.setText("Insert Your Data");

        labelNameregister.setFont(new java.awt.Font("Cascadia Mono", 1, 13)); // NOI18N
        labelNameregister.setText("Name :");

        labelUsernameregister.setFont(new java.awt.Font("Cascadia Mono", 1, 13)); // NOI18N
        labelUsernameregister.setText("Username :");

        labelPasswordregister.setFont(new java.awt.Font("Cascadia Mono", 1, 13)); // NOI18N
        labelPasswordregister.setText("Password :");

        labelPasswordregister2.setFont(new java.awt.Font("Cascadia Mono", 1, 13)); // NOI18N
        labelPasswordregister2.setText("Re-type Password :");

        btRegister2.setText("Register");
        btRegister2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btRegister2ActionPerformed(evt);
            }
        });

        labelAlamat.setFont(new java.awt.Font("Cascadia Mono", 1, 13)); // NOI18N
        labelAlamat.setText("Alamat:");

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
            .addGroup(layout.createSequentialGroup()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addGroup(layout.createSequentialGroup()
                                .addGap(187, 187, 187)
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                                    .addComponent(labelNameregister)
                                    .addComponent(labelPasswordregister)
                                    .addComponent(labelPasswordregister2)
                                    .addComponent(labelAlamat))
                                .addGap(18, 18, 18))
                            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                .addComponent(labelUsernameregister)
                                .addGap(20, 20, 20)))
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                                .addComponent(TFnameregister, javax.swing.GroupLayout.DEFAULT_SIZE, 240, Short.MAX_VALUE)
                                .addComponent(pwRegister)
                                .addComponent(pwRegister2)
                                .addComponent(TFusernameregister, javax.swing.GroupLayout.Alignment.TRAILING)
                                .addComponent(TFAlamatregister))
                            .addGroup(layout.createSequentialGroup()
                                .addComponent(btRegister2, javax.swing.GroupLayout.PREFERRED_SIZE, 98, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                .addComponent(labelWarning, javax.swing.GroupLayout.PREFERRED_SIZE, 289, javax.swing.GroupLayout.PREFERRED_SIZE))))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(319, 319, 319)
                        .addComponent(titleRegister))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(371, 371, 371)
                        .addComponent(labelRegister)))
                .addContainerGap(136, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(titleRegister)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(labelRegister)
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(labelNameregister)
                    .addComponent(TFnameregister, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(labelAlamat)
                    .addComponent(TFAlamatregister, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 17, Short.MAX_VALUE)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(labelUsernameregister)
                    .addComponent(TFusernameregister, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(labelPasswordregister)
                    .addComponent(pwRegister, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(labelPasswordregister2)
                    .addComponent(pwRegister2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(btRegister2, javax.swing.GroupLayout.PREFERRED_SIZE, 35, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(labelWarning, javax.swing.GroupLayout.PREFERRED_SIZE, 35, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(52, 52, 52))
        );

        pack();
        setLocationRelativeTo(null);
    }// </editor-fold>//GEN-END:initComponents

    private void minimizeRegisterMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_minimizeRegisterMouseClicked
        // TODO add your handling code here:
        this.setState(1);
    }//GEN-LAST:event_minimizeRegisterMouseClicked

    private void xRegisterMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_xRegisterMouseClicked
        // TODO add your handling code here:
        System.exit(0);
    }//GEN-LAST:event_xRegisterMouseClicked

    private void btRegister2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btRegister2ActionPerformed
        // TODO add your handling code here:
        String nama = TFnameregister.getText();
        String alamat = TFAlamatregister.getText();
        String username = TFusernameregister.getText();
        String password = new String(pwRegister.getPassword());
        String repassword = new String(pwRegister2.getPassword());
        
        new ControllerClient(null, this).clientRegister(nama, username, password, repassword, alamat, labelWarning);
    }//GEN-LAST:event_btRegister2ActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(Register.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(Register.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(Register.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(Register.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new Register().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JTextField TFAlamatregister;
    private javax.swing.JTextField TFnameregister;
    private javax.swing.JTextField TFusernameregister;
    private javax.swing.JButton btRegister2;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JLabel labelAlamat;
    private javax.swing.JLabel labelNameregister;
    private javax.swing.JLabel labelPasswordregister;
    private javax.swing.JLabel labelPasswordregister2;
    private javax.swing.JLabel labelRegister;
    private javax.swing.JLabel labelUsernameregister;
    private javax.swing.JLabel labelWarning;
    private javax.swing.JLabel minimizeRegister;
    private javax.swing.JPasswordField pwRegister;
    private javax.swing.JPasswordField pwRegister2;
    private javax.swing.JLabel titleRegister;
    private javax.swing.JLabel xRegister;
    // End of variables declaration//GEN-END:variables
}
